import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  card: {
    width: '46%',
    marginVertical: 4,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 15,
    paddingVertical: 14,
    shadowColor: '#BABABA',
    shadowOpacity: 1,
    shadowRadius: 2,
    shadowOffset: {width: 4, height: 4},
    elevation: 2,
  },
  background: {
    backgroundColor: '#ffffffa3',
    borderRadius: 100,
    width: 100,
    height: 100,
    marginTop: 10,
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  image: {
    width: 135,
    height: 135,
    marginTop: -24,
  },
  name: {
    fontWeight: '700',
    fontSize: 18,
    color: '#464646',
    marginTop: 20,
  },
  containerType: {
    flexDirection: 'row',
    width: '100%',
    justifyContent: 'space-evenly',
    marginBottom: 10,
    marginTop: 8,
  },
  type: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 15,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#606060',
    shadowOpacity: 0.5,
    shadowRadius: 1.5,
    shadowOffset: {
      width: 2,
      height: 3,
    },
    elevation: 4,
    flexDirection: 'row',
  },
  typeText: {
    fontSize: 12,
    fontWeight: '500',
    color: 'white',
    textAlign: 'center',
  },
  loadingCard: {
    width: '46%',
    height: 160,
    textAlign: 'center',
    padding: 10,
  },
  imageType: {width: 12, height: 12, marginRight: 3},
  ContainerTab: {
    width: '99%',
    paddingVertical: 2,
    paddingBottom: 4,
  },
  touchableType: {
    justifyContent: 'center',
    alignItems: 'center',
    width: 34,
    height: 34,
    marginHorizontal: 6,
    borderRadius: 100,
    borderWidth: 1.5,
  },
});
